import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter_test/flutter_test.dart';
import 'package:phonefarm_worker/protocol_v1.dart';

void main() {
  group('ProtocolV1 Dart Codec', () {
    test('Roundtrip encoding and decoding for TENSOR frame', () {
      final payload = Uint8List.fromList([1, 2, 3, 4, 5, 6, 7, 8]);
      final metadata = {
        'request_id': 'req_test_001',
        'segment_id': 0,
        'dtype': 'float32',
        'shape': [1, 2],
      };
      final frame = Frame(MessageType.tensor, metadata, payload);

      final encoded = encodeFrame(frame);
      final decoded = decodeFrame(encoded);

      expect(decoded.messageType, MessageType.tensor);
      expect(decoded.metadata['request_id'], 'req_test_001');
      expect(decoded.metadata['segment_id'], 0);
      expect(decoded.metadata['dtype'], 'float32');
      expect(decoded.metadata['shape'], [1, 2]);
      expect(decoded.payload, payload);
    });

    test('Matches Python golden frame binary representation', () {
      // Golden frame generated by python:
      // Frame(MessageType.TENSOR, {"dtype": "float32", "request_id": "r1", "shape": [1, 4]}, b"abcd")
      const goldenHex =
          '504641520103000000330000000000000004ed82cd117b226474797065223a22666c6f61743332222c22726571756573745f6964223a227231222c227368617065223a5b312c345d7d61626364';

      final goldenBytes = Uint8List(goldenHex.length ~/ 2);
      for (int i = 0; i < goldenHex.length; i += 2) {
        goldenBytes[i ~/ 2] = int.parse(goldenHex.substring(i, i + 2), radix: 16);
      }

      final decoded = decodeFrame(goldenBytes);
      expect(decoded.messageType, MessageType.tensor);
      expect(decoded.metadata['request_id'], 'r1');
      expect(decoded.metadata['dtype'], 'float32');
      expect(decoded.metadata['shape'], [1, 4]);
      expect(decoded.payload, utf8.encode('abcd'));
    });

    test('Rejects corrupted payload with checksum mismatch', () {
      final frame = Frame(
        MessageType.tensor,
        {'request_id': 'r1'},
        Uint8List.fromList(utf8.encode('valid_payload')),
      );
      final encoded = encodeFrame(frame);

      // Corrupt the last byte of payload
      final corrupted = Uint8List.fromList(encoded);
      corrupted[corrupted.length - 1] ^= 0xFF;

      expect(
        () => decodeFrame(corrupted),
        throwsA(isA<ProtocolException>().having(
          (e) => e.message,
          'message',
          contains('checksum mismatch'),
        )),
      );
    });

    test('Rejects invalid magic and version', () {
      final frame = Frame(MessageType.hello, {'worker_id': 'w1'});
      final encoded = encodeFrame(frame);

      // Corrupt magic
      final badMagic = Uint8List.fromList(encoded);
      badMagic[0] = 0x00;
      expect(() => decodeFrame(badMagic), throwsA(isA<ProtocolException>()));

      // Corrupt version
      final badVersion = Uint8List.fromList(encoded);
      badVersion[4] = 99;
      expect(() => decodeFrame(badVersion), throwsA(isA<ProtocolException>()));
    });

    test('FrameAccumulator reassembles fragmented chunks correctly', () {
      final frame1 = Frame(
        MessageType.hello,
        {'worker_id': 'phone_01'},
      );
      final frame2 = Frame(
        MessageType.tensor,
        {'request_id': 'r2', 'shape': [1, 4]},
        Uint8List.fromList([10, 20, 30, 40]),
      );

      final bytes1 = encodeFrame(frame1);
      final bytes2 = encodeFrame(frame2);
      final combined = [...bytes1, ...bytes2];

      final accumulator = FrameAccumulator();

      // Feed in 7-byte chunks
      final readFrames = <Frame>[];
      for (int i = 0; i < combined.length; i += 7) {
        final end = (i + 7 < combined.length) ? i + 7 : combined.length;
        accumulator.add(combined.sublist(i, end));
        while (true) {
          final f = accumulator.tryReadFrame();
          if (f == null) break;
          readFrames.add(f);
        }
      }

      expect(readFrames.length, 2);
      expect(readFrames[0].messageType, MessageType.hello);
      expect(readFrames[0].metadata['worker_id'], 'phone_01');
      expect(readFrames[1].messageType, MessageType.tensor);
      expect(readFrames[1].metadata['request_id'], 'r2');
      expect(readFrames[1].payload, Uint8List.fromList([10, 20, 30, 40]));
    });
  });
}
